server:
  port: 10086
spring:
  application:
    name: leyou-registry
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:${server.port}/eureka
    register-with-eureka: true #是否注册到eureka
    fetch-registry: false #是否拉取服务列表
  server:
    enable-self-preservation: false #关闭自我保护自制
    eviction-interval-timer-in-ms: 5000 #每隔5秒钟，进行一次服务列表清理
