server:
  port: 8084
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
spring:
  application:
    name: goods-web

  rabbitmq:
    virtual-host: /leyou
    username: leyou
    password: leyou
    host: 192.168.74.129

  thymeleaf:
    cache: false

