server:
  port: 8085


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/leyou
    password: root
    username: root
    driver-class-name: com.mysql.jdbc.Driver

#配置redis
  redis:
    host: 127.0.0.1

  application:
    name: user-service

#配置rabbitmq
  rabbitmq:
    virtual-host: /leyou
    username: leyou
    password: leyou
    host: 192.168.74.129
#    template:
#      exchange: leyou.sms.exchange
#    publisher-confirms: true

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka

  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
mybatis:
  type-aliases-package: com.leyou.user.pojo
