server:
  port: 8086
spring:
  rabbitmq:
    virtual-host: /leyou
    username: leyou
    password: leyou
    host: 192.168.74.129
  application:
    name: sms-service

leyou:
  sms:
    accessKeyId: JWffwFJIwada # 你自己的accessKeyId
    accessKeySecret: aySRliswq8fe7rF9gQyy1Izz4MQ # 你自己的AccessKeySecret
    signName: 乐优商城 # 签名名称
    verifyCodeTemplate: SMS_133976814 # 模板名称




