server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/leyou
    hikari:
      max-lifetime: 28830000 #一个连接的生命时长，超时而且没被使用就释放，缺省:30分钟，
      #建议设置比数据库超时时长少30秒，参考MySQL wait_timeout参数（show variables like '%timeout%';）
      maximum-pool-size: 9 # 连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
  #配置rabbitmq
  rabbitmq:
    virtual-host: /leyou
    username: leyou
    password: leyou
    host: 192.168.74.129
    template:
      exchange: leyou.item.exchange
    publisher-confirms: true



eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-expiration-duration-in-seconds: 10 #10s不发送就过期
    lease-renewal-interval-in-seconds: 5 # 5s发送一次心跳包
logging:
  level:
    com.leyou.item.mapper: debug


