server:
  port: 10010

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    fetch-registry: true
    register-with-eureka: true


spring:
  application:
    name: leyou-gateway

zuul:
  prefix: /api
  routes:
    item-service: /item/** #商品服务
    search-service: /search/** #搜索服务
    user-service: /user/**  #用户服务
  ignored-services:
    - upload-service  #不对文件上传进行路由